### ISSUE TITLE
Alembic permission add shortcut

### ISSUE THREAD

**Issue by nZac** [level12/keg-bouncer#5]
A helpful function to create a permission, add it to a group/bundle would be rather helpful.

For example,

``` python

def alembic_create_permission(op, permissions, groups=None, bundles=None):
    for perm in permissions:
        permission_create(perm)
        add_perm_to_groups(perm, groups)
        add_perm_to_bundles(perm, bundles)
```

Obviously the code might look a little different than this, but you get the point.

**Comment by 3noch** [comment]
I've wanted this as well. The migrations I've written use raw SQL so I didn't port them to KegBouncer (since it can't use raw SQL).
