### ISSUE TITLE
Add a COPYING file

### ISSUE THREAD

**Issue by cwebber** [level12/keg-bouncer#7]
The setup.py metadata says this is BSD licensed, which is great, but to really formalize it a COPYING file is needed.  Could you provide one?

**Comment by nZac** [comment]
Thanks @cwebber we will get something put in tomorrow. 

@3noch can you take a look at how @rsyring has https://github.com/level12/keg setup with the license.txt file. I think we prefer that method over the GNU COPYING file. IMO it don't matter all that much but LICENSE or COPYING should exist.

**Comment by rsyring** [comment]
Please use `license.txt` or `LICENSE` (ala Flask & company).

**Comment by rsyring** [comment]
I'm really surprised anyone is using this or cares about it outside Level 12.  :)

**Comment by cwebber** [comment]
Thank you! :)
