### ISSUE TITLE
Update readme to support pypi

### ISSUE THREAD

**Issue by nZac** [level12/keg-bouncer#8]
I think we will need to drop the use of `:code:`

**Comment by rsyring** [comment]
You mean `.. default-role:: code`?  I don't see us using :code: in the source.

**Comment by rsyring** [comment]
```
pip install readme
readme --long-description
```

Should verify the rst in a way that verifies compatibility with pypi.

**Comment by nZac** [comment]
Hmm, when I looked into the problem it was because docutils is 0.8.0 or something in that 0.8 line. And the `:code:` directive isn't supported there.

See: 

``` rst
.. code:: python

   from sqlalchemy import import Column, Integer, String

   Base = sqlalchemy.ext.declarative.declarative_base()

   class User(Base, keg_bouncer.model.mixins.UserMixin):
       __tablename__ = 'users'
       id = Column(Integer, primary_key=True)
```

in the readme.

**Comment by rsyring** [comment]
I'm sorry, I was searching for ":code:".
